# Generated by Django 4.0.5 on 2022-06-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dep_name',
            field=models.CharField(default='department name', max_length=70),
        ),
    ]
