# Generated by Django 4.0.5 on 2022-06-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
    ]
