# Generated by Django 4.0.5 on 2022-06-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_departments_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_phone', models.CharField(max_length=10)),
                ('patient_email', models.EmailField(max_length=254)),
                ('Booking_Date', models.DateField()),
                ('Booked_On', models.DateField(auto_now=True)),
                ('Doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
            ],
        ),
    ]
