# Generated by Django 3.2.10 on 2022-07-19 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_department_dep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
