# Generated by Django 3.2.10 on 2022-07-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220719_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_Date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_time',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient_address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient_phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
