# Generated by Django 3.2.10 on 2022-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220719_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_time',
            field=models.TimeField(blank=True, default=''),
        ),
    ]
