# Generated by Django 4.0.6 on 2022-07-27 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_mymodel_user_register_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='username',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='user_register',
            name='password_verify',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
