# Generated by Django 4.0.6 on 2022-07-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_username_user_register_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='password_verify',
        ),
        migrations.AddField(
            model_name='user_register',
            name='password2',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_register',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='password',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
