# Generated by Django 4.0.6 on 2022-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_user_register_password_verify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='password2',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
