# Generated by Django 4.0.6 on 2022-07-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_user_register_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='password',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='username',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
