# Generated by Django 4.0.6 on 2022-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_user_register_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='password',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='password2',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
