# Generated by Django 4.0.6 on 2022-07-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_user_register_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(max_length=200, null=True)),
                ('Phonenum', models.CharField(max_length=12, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Messages', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User_register',
        ),
    ]
