# Generated by Django 4.0.6 on 2022-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Formemail',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
