# Generated by Django 4.0.6 on 2022-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_contact_formemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Formemail',
            new_name='Form_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phonenum',
            new_name='Phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='Mesaages_On',
            field=models.DateField(auto_now=True),
        ),
    ]
