# Generated by Django 4.0.6 on 2022-07-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_firstname_contact_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Mesaages_On',
            new_name='Messaged_On',
        ),
    ]
