# Generated by Django 4.0.6 on 2022-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_mesaages_on_contact_messaged_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booked_On_Time',
            field=models.TimeField(auto_now=True),
        ),
    ]
